### PR TITLE
Operon competition entry

### PR DESCRIPTION
**Pull request by foolnotion**
Competition Checklist:
- [x] title of this PR is meaningful, i.e. "method X for comp"
- [x] A folder has been added to `submission/` with a meaningful name corresponding to your method name.
- The added folder includes these elements:
    - [x] `metadata.yml` (**required**): A file describing your submission, following the descriptions in `example/metadata.yml`.  
    - [x] `regressor.py` (**required**): a Python file that defines your method, named appropriately. See [submission/feat-example/regressor.py](https://github.com/cavalab/srbench/blob/Competition2022/submission/feat-example/regressor.py) for complete documentation.  It contains:
        - [x]  `est`: a sklearn-compatible `Regressor` object. 
        - [x]  `model(est, X=None)`: a function that returns a [**sympy-compatible**](https://www.sympy.org) string specifying the final model. It can optionally take the training data as an input argument. See [guidance below](###-returning-a-sympy-compatible-model-string). 
        - [x]  `eval_kwargs` (optional): a dictionary that can specify method-specific arguments to `evaluate_model.py`.
        
    - [ ] `LICENSE` *(optional)* A license file
    - [x] `environment.yml` *(optional)*: a [conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) that specifies dependencies for your submission. 
    - [x] `install.sh` *(optional)*: a bash script that installs your method. 
    - [ ] additional files *(optional)*: you may include a folder containing the code for your method in the submission. 

I have verified that:

- [x] install scripts do not require sudo permissions. 
- [x] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Refer to the [competition guide]( https://cavalab.org/srbench/competition-guide/ ) if you are unsure about any steps. 
If you don't find an answer, ping us!

### CODE REVIEW

**Comment by foolnotion** [comment]
In this submission, I try to use [OptunaSearchCV](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.OptunaSearchCV.html) to tune the hyperparameters.

The grid search is allowed to use 3/4 of the maximum time (i.e. 45 min). Operon itself is always time-limited to 15 min per run.
If I understand this correctly, this would allow enough time for `est.fit()` to finish, even with `refit=True`, so that the time limit is always respected.

**Comment by lacava** [comment]
that all sounds good @foolnotion . Thanks for your submission! Ready to merge when you are. It's easier to edit your submission before I merge, but you can always update by submitting a new copy in the submission folder.

**Comment by foolnotion** [comment]
Thanks @lacava ! Please hold off the merge for now, I suspect I might need another commit to fix a minor issue. Everything should be ready to merge by tomorrow.

**Comment by foolnotion** [comment]
I think this is ready to merge. I did my best to ensure determinism even when nested with optuna.

Main highlights of this submission:

- Operon nested with Optuna for hyperparameter tuning (45 min timeout or 50 trials, whichever happens first) 
- NSGA-II with ϵ-dominance and two objectives: R2 (coefficient of determination) and length
- Eigen::LevenbergMarquardt (instead of TinySolver from Ceres) for coeff tuning (but still uses Ceres jets for autodiff)
- C++20 dev branches of operon/pyoperon
    * https://github.com/heal-research/operon/commit/930b4ad1e4c013ff88a14ec3441eb7662b9146f3
    * https://github.com/heal-research/pyoperon/commit/e4ef1047240b2df66555ddd54463ab707863aae6

**Comment by lacava** [comment]
it looks like your fork's CI was triggered on a push, and now your submission is in `official competitors` instead of `submission`. This is going to prevent the tests from triggering.

**Comment by foolnotion** [comment]
I did notice the bot moving the submission to the official folder, but assumed this was intended after CI success. For what its worth I am passing the local test from here https://github.com/cavalab/srbench/discussions/81#discussioncomment-2546257

Should I make a new PR or how do you want to proceed?

**Comment by lacava** [comment]
in keeping with the protocols, it would be best for you to move the folder back to `submission`. I think you can just push a commit that way, and I wonder if you can turn off the `ci_push.yml` action on your fork? 

Otherwise I can try to set up the tests to trigger on push for official competitor entries as well, but I probably won't get to that by the time submissions close.

**Pull request merged**
