### PR TITLE
Bingo submission for 2024 benchmark

### PR DESCRIPTION
**Pull request by gbomarito**
This PR updates bingo to reference the main repository, which now also supports the get_population method for the new benchmark.

There is also a minor update to the test_population method.  From what I can tell there is either a typo in the original implementation or the implementation depends on a specific version of pandas to work correctly (could be an issue with my pandas version as well).

### CODE REVIEW

**Review by foolnotion — CHANGES_REQUESTED** [review]
Just a few minor issues:

- put `regressor.py` in `algorithms/bingo`, not in `experiments/methods/bingo`
- fix a revision in `install.sh` when you clone bingo
- the conda environment should be named `srbench-bingo` (I think this is expected by the bash scripts see e.g. https://github.com/cavalab/srbench/blob/92e8f35a4ca54a8438e96aca35dc2a934feaa0b2/local_ci.sh#L5)

**Comment by gbomarito** [comment]
thanks for the review, let me know if there are any more issues

**Review by foolnotion — APPROVED** [review]

**Review by foolnotion — APPROVED** [review]

**Comment by foolnotion** [comment]
Maybe one small thing remaining: the fix in `test_population.py`, I also encountered that error today, this fix probably shouldn't be merged together with your submission.

**Review by foolnotion — COMMENTED** [review]
I would revert changes in `experiment/test_population.py` for now, but let's see what the others say.

**Pull request merged**
