### PR TITLE
Docker fixes

### PR DESCRIPTION
**Pull request by MilesCranmer**
This PR is #59 but with a few extra changes:

- Fixes the platform to `linux/amd64` only, which enables this docker container to be built on any system whatsoever. (necessary since many of the conda packages are architecture-specific).
- The dockerfile itself has been simplified, and the NVIDIA/GPU-specific parts have been removed. I think those should be up to the user to configure in a Dockerfile which depends on this one, since many systems do not have a GPU, and NVIDIA files are different by system.
- Builds with micromamba instead of conda, which significantly reduces build time.
- Also includes `conda` so that the `install.sh` files can proceed without modification. `mamba` and `conda` use the same structure so they can both be used.
- Adds a GitHub action to test the building of the container.

The CI right now just tests if the container is buildable, but does not run the tests within the docker yet. Those can be added later.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Can also use caching of the docker image:

https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

**Comment by MilesCranmer** [comment]
@foolnotion I also merged the commits from your PR on @yoshitomo-matsubara's repository. It looks like your changes cavalab/srbench:master supersede those changes? But let me know if anything looks off here.

**Comment by MilesCranmer** [comment]
Actually maybe the NVIDIA parts should be left in. @yoshitomo-matsubara do you know if they affect the build for systems not using GPUs?

**Comment by yoshitomo-matsubara** [comment]
@MilesCranmer I think I tested the original docker file with the NVIDIA parts on a local machine (with no GPUs), so it won't affect the build for those with no GPUs

**Review by lacava — CHANGES_REQUESTED** [review]
looks like the install files were deleted; did you move them?

**Comment by MilesCranmer** [comment]
No but it looks like changing `bash $install_file` to `$install_file` in `install.sh` didn't work as intended and results in the above error. I was trying to keep the same shell env when running the install files since it complains it can't find conda otherwise.

**Comment by MilesCranmer** [comment]
Argh, I really can't seem get this working after many hours. The conda install runs fine, but after this, the docker container to forget that I've run `conda init bash` and keeps complaining about this. @yoshitomo-matsubara or @foolnotion want to have a stab?

**Comment by lacava** [comment]
> Argh, I really can't seem get this working after many hours. The conda install runs fine, but after this, the docker container to forget that I've run `conda init bash` and keeps complaining about this. @yoshitomo-matsubara or @foolnotion want to have a stab?

I should be able to make a pass in the next couple weeks...

**Comment by foolnotion** [comment]
Next week I will have a look as well.

**Comment by lacava** [comment]
>The conda install runs fine, but after this, the docker container to forget that I've run `conda init bash` and keeps complaining about this. 

The fix seems to be to specify the environment as a precursor to SHELL as 

`SHELL ["conda", "run", "-n", "srbench", "/bin/bash", "-c"]`

I'm able to build the Docker Image fine, but I've moved on to attempting to use the image (and cache it) for the tests on the  [cavalab:docker-fix](https://github.com/cavalab/srbench/tree/docker-fix) branch.

**Comment by lacava** [comment]
moved to PR #75

**Pull request closed without merging**
