### PR TITLE
method GPZGD for comp

### PR DESCRIPTION
**Pull request by grantdick**
Competition Checklist:
- [x] title of this PR is meaningful, i.e. "method X for comp"
- [x] A folder has been added to `submission/` with a meaningful name corresponding to your method name.
- The added folder includes these elements:
    - [x] `metadata.yml` (**required**): A file describing your submission, following the descriptions in `example/metadata.yml`.  
    - [x] `regressor.py` (**required**): a Python file that defines your method, named appropriately. See [submission/feat-example/regressor.py](https://github.com/cavalab/srbench/blob/Competition2022/submission/feat-example/regressor.py) for complete documentation.  It contains:
        - [x]  `est`: a sklearn-compatible `Regressor` object. 
        - [x]  `model(est, X=None)`: a function that returns a [**sympy-compatible**](https://www.sympy.org) string specifying the final model. It can optionally take the training data as an input argument. See [guidance below](###-returning-a-sympy-compatible-model-string). 
        - [x]  `eval_kwargs` (optional): a dictionary that can specify method-specific arguments to `evaluate_model.py`.
        
    - [ ] `LICENSE` *(optional)* A license file
    - [x] `environment.yml` *(optional)*: a [conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) that specifies dependencies for your submission. 
    - [x] `install.sh` *(optional)*: a bash script that installs your method. 
    - [x] additional files *(optional)*: you may include a folder containing the code for your method in the submission. 

I have verified that:

- [x] install scripts do not require sudo permissions. 
- [x] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Refer to the [competition guide]( https://cavalab.org/srbench/competition-guide/ ) if you are unsure about any steps. 
If you don't find an answer, ping us!

### CODE REVIEW

**Comment by grantdick** [comment]
Apologies - got confused with the deadline and thought it was end of today. 

If there's a chance that you can accept this entry, I am wondering why the module gpzgd.py is not being found - it is right next to the regressor.py file, so I would have though there would be no problem with it.

**Comment by folivetti** [comment]
could you try to change the import to `from .gpzgd import GPZGD`? (notice the dot before gpzgd)

**Comment by folivetti** [comment]
also you might need an empty `__init__.py` file at the same folder as your python script

**Comment by grantdick** [comment]
Thanks very much - I think that I may have made some progress by moving the definition of the class directly into regressor.py.

However, now the command line application dist/regressor isn't found (it gets compiled correctly in the "Install SR method" step, but I assume that it needs to be copied somewhere?)

**Comment by foolnotion** [comment]
> Thanks very much - I think that I may have made some progress by moving the definition of the class directly into regressor.py. However, now the command line application dist/regressor isn't found (it gets compiled correctly in the "Install SR method" step, but I assume that it needs to be copied somewhere?)

You can try copying it to `${CONDA_PREFIX}/bin` in your `install.sh` script. You probably also need to make sure that the executable can find and open the data file.

**Comment by foolnotion** [comment]
If it's in `${CONDA_PREFIX}/bin` it won't need another `bin` added in front of it in your subprocess call. I would also rename the executable to something more descriptive like `gpzgd_regressor` and make sure it is marked as such `chmod +x`

**Comment by lacava** [comment]
Hi @grantdick, 

Thanks for your submission! Unfortunately we decided to be strict with the deadline to be fair and consistent to competitors (e.g. https://github.com/cavalab/srbench/pull/120) . So we can't include this as a competition entry for the prize. 

However, we will still test this method, and are happy to include it (and you) in our manuscript re: the competition and going forward. Sorry to disappoint.

**Comment by grantdick** [comment]
Hi Bill,

Thanks - very happy with that option. Not at all disappointed!

Looking forward to seeing the comparisons.

Cheers,
Grant.

**Pull request merged**
