### PR TITLE
PS-Tree

### PR DESCRIPTION
**Pull request by hengzhe-zhang**
Hello! I spent one day changing my algorithm package so that it can output a sympy-compatible model now. The modification is made on the open-source package, so there is no need for modification here. However, because the new requirements require me to push the pull request to the "dev" branch, I open this new pull request and hope that this version of the package will be able to satisfy the SRBench requirement.

### CODE REVIEW

**Comment by Hengzhe-Zhang** [comment]
Hello! @lacava  I have fixed a bug about printing the symbolic model and the CI works fine now.

**Review by lacava — CHANGES_REQUESTED** [review]
please add 6 hyperparameter combinations to `hyper_params`, unless you don't want PSTree to be tuned

**Comment by Hengzhe-Zhang** [comment]
If I have more than one chance to submit my algorithm, I think I don't need to tune PS-Tree this time. Based on my own experience, the default parameter of PS-Tree works well.

**Comment by lacava** [comment]
> @lacava Thanks! If I have more than one chance to submit my algorithm, I think I don't need to tune PS-Tree this time. Based on my own experience, the default parameter of PS-Tree works well.

I'm not planning to run PSTree multiple times after conducting the experiment - it is very long. So, if you want to do any tuning you should add them now. If not I will go with default parameters.

**Comment by Hengzhe-Zhang** [comment]
@lacava Thanks! I understand your concern. According to my current experience, PS-Tree can match Operon's speed if we run all experiments with the default hyper-parameter. I only used a 96-core Huawei server for my experiment, and I was able to complete all of them in a single night. If that really bothers you, I would be happy to provide a parameter grid, but it will take some time.

**Comment by lacava** [comment]
hi @hengzhe-zhang I think to do an apples-to-apples time comparison we need 6 tuneable settings (see issue #24  for discussion). Could also consider reporting training instance time within CV, but that is not measured currently.

**Comment by lacava** [comment]
@hengzhe-zhang I'm going to merge this and open an issue about the parameters.

**Pull request merged**
