### PR TITLE
add E2ET method

### PR DESCRIPTION
**Pull request by pakamienny**
Competition Checklist:
- [x] title of this PR is meaningful, i.e. "method X for comp"
- [x] A folder has been added to `submission/` with a meaningful name corresponding to your method name.
- The added folder includes these elements:
    - [x] `metadata.yml` (**required**): A file describing your submission, following the descriptions in `example/metadata.yml`.  
    - [x] `regressor.py` (**required**): a Python file that defines your method, named appropriately. See [submission/feat-example/regressor.py](https://github.com/cavalab/srbench/blob/Competition2022/submission/feat-example/regressor.py) for complete documentation.  It contains:
        - [x]  `est`: a sklearn-compatible `Regressor` object. 
        - [x]  `model(est, X=None)`: a function that returns a [**sympy-compatible**](https://www.sympy.org) string specifying the final model. It can optionally take the training data as an input argument. See [guidance below](###-returning-a-sympy-compatible-model-string). 
        - [x]  `eval_kwargs` (optional): a dictionary that can specify method-specific arguments to `evaluate_model.py`.
        
    - [ ] `LICENSE` *(optional)* A license file
    - [ ] `environment.yml` *(optional)*: a [conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) that specifies dependencies for your submission. 
    - [ ] `install.sh` *(optional)*: a bash script that installs your method. 
    - [ ] additional files *(optional)*: you may include a folder containing the code for your method in the submission. 

I have verified that:

- [x] install scripts do not require sudo permissions. 
- [x] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Refer to the [competition guide]( https://cavalab.org/srbench/competition-guide/ ) if you are unsure about any steps. 
If you don't find an answer, ping us!

### CODE REVIEW

**Comment by pakamienny** [comment]
Hi ! this is my first try to submit for the SRBench's competition. 
I tried following William's answer here https://github.com/cavalab/srbench/discussions/81#discussioncomment-2546257 on how to get the submission running. Running directly test_evaluate on our method (E2ET) goes perfect, however there is an issue when importing stuff using pytest (which seems to be a common issue on stackoverflow, though I could not really get around it). Any idea? 

What about running with CI (which I am not familiar at all with). what is the associated command? 

Please let me know how I can improve my PR :) thanks!

**Comment by lacava** [comment]
hey @pakamienny , great, thanks for your submission! The install and tests are running and can be checked above, e.g.: https://github.com/cavalab/srbench/runs/5996899965?check_suite_focus=true

**Comment by lacava** [comment]
Looks like there's an issue with pip finding the right torch version:
```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.11.0+cu113
```

**Comment by pakamienny** [comment]
Hi @lacava, it looks like we finally passed the test, but the CI somehow fails when adding us as a competitor :) do you know whether this comes from us? 
Thanks!

**Comment by lacava** [comment]
hi @pakamienny , great. Yes, it looks like the error is on our end.. just a bad commit ref I think. bear with us, we'll get it fixed!

**Comment by pakamienny** [comment]
perfect, thanks, please let me know when this is solved if I have to do something for the submission.

**Comment by lacava** [comment]
this is the issue: https://github.com/github/docs/issues/15319

I think I fixed it; @pakamienny could you merge with the upstream commits on Competition2022?

**Comment by pakamienny** [comment]
> this is the issue: [github/docs#15319](https://github.com/github/docs/issues/15319)
> 
> I think I fixed it; @pakamienny could you merge with the upstream commits on Competition2022?
> 
> EDIT: i'm going to try a merge commit and see what happens :)

Looks like it worked @lacava. This mean we are official competitors right? Just to be sure, we can still update the model until end of competition, via PR?

**Comment by lacava** [comment]
@pakamienny yes! thanks for your submission, you are official competitors. I will be in touch if we run into any issues. 

And yes, you are free to update your submission until the submission deadline. Just submit a PR that changes your submission folder. The tests are triggered by changes in that path.

Note: you can totally remove `eval_kwargs` and the pretrain function if you aren't using them.

**Pull request merged**
