### PR TITLE
[Competition] Add PySR method

### PR DESCRIPTION
**Pull request by MilesCranmer**
**This is a work in progress and not my final submission**

Competition Checklist:
- [x] title of this PR is meaningful, i.e. "method X for comp"
- [x] A folder has been added to `submission/` with a meaningful name corresponding to your method name.
- The added folder includes these elements:
    - [x] `metadata.yml` (**required**): A file describing your submission, following the descriptions in `example/metadata.yml`.  
    - [x] `regressor.py` (**required**): a Python file that defines your method, named appropriately. See [submission/feat-example/regressor.py](https://github.com/cavalab/srbench/blob/Competition2022/submission/feat-example/regressor.py) for complete documentation.  It contains:
        - [x]  `est`: a sklearn-compatible `Regressor` object. 
        - [x]  `model(est, X=None)`: a function that returns a [**sympy-compatible**](https://www.sympy.org) string specifying the final model. It can optionally take the training data as an input argument. See [guidance below](###-returning-a-sympy-compatible-model-string). 
        - [x]  `eval_kwargs` (optional): a dictionary that can specify method-specific arguments to `evaluate_model.py`.
        
    - [x] `LICENSE` *(optional)* A license file
    - [x] `environment.yml` *(optional)*: a [conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) that specifies dependencies for your submission. 
    - [x] `install.sh` *(optional)*: a bash script that installs your method. 
    - [x] additional files *(optional)*: you may include a folder containing the code for your method in the submission. 

I have verified that:

- [x] install scripts do not require sudo permissions. 
- [x] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Refer to the [competition guide]( https://cavalab.org/srbench/competition-guide/ ) if you are unsure about any steps. 
If you don't find an answer, ping us!

### CODE REVIEW

**Comment by MilesCranmer** [comment]
@srbench-comp I was wondering if you could help me with getting the test to pass. 

I'm struggling with an issue related to the sympy representation. I can run the test manually just fine, but when I run it through `pytest`, it seems to show this issue:
```
TypeError: 'str' object is not callable
```
any idea what this is?

I can manually run the functions `test_import("pysr"), test_evaluate("pysr"), test_sympy("pysr")` inside test_submission.py just fine, but for some reason inside pytest, it seems to break.

**Comment by MilesCranmer** [comment]
For some reason it seems to work now!

Anyways I need to make some edits and then resubmit.

**Comment by MilesCranmer** [comment]
Hey @lacava @srbench-comp, this should be ready to submit now.

**Comment by MilesCranmer** [comment]
Okay the error I mentioned above is back. I think it just went away because it only appears stochastically during the test (only when a symbol appears in my formula, but constants are fine).

This is a bit problematic.

Here is the output:
```
ValueError: Error from parse_expr with transformed code: "(Symbol ('x0' )*cos (ssqrt (Symbol ('x1' ))))"

The above exception was the direct cause of the following exception:

ml = 'pysr'

    def test_evaluate(ml):
        """Dataset evaluation"""
        algorithm = get_algorithm(ml)
        if 'eval_kwargs' in dir(algorithm):
            eval_kwargs = algorithm.eval_kwargs
    
    
>       json_file = evaluate_model(dataset,
                       results_path,
                       random_state,
                       ml,
                       algorithm.est,
                       algorithm.model,
                       test=True, # testing
                       **eval_kwargs
                      )

test_submission.py:[77](https://github.com/cavalab/srbench/runs/6430251573?check_suite_focus=true#step:9:77): 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
evaluate_model.py:161: in evaluate_model
    y_pred = np.asarray(pred(X)).reshape(-1,1)
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/pysr/sr.py:949: in predict
    self.refresh()
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/pysr/sr.py:932: in refresh
    self.equations = self.get_hof()
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/pysr/sr.py:1464: in get_hof
    eqn = sympify(eqn_row["equation"], locals=local_sympy_mappings)
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/sympy/core/sympify.py:495: in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py:1105: in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py:1096: in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
/usr/share/miniconda3/envs/srcomp-pysr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py:[91](https://github.com/cavalab/srbench/runs/6430251573?check_suite_focus=true#step:9:91)5: in eval_expr
    expr = eval(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: 'str' object is not callable
```

It seems to throw an error when I internally call `sympify`. Perhaps because `srbench` internally is declaring `sympy` Symbols, then I am unable to use the same symbols when running `sympify`? 

Note that I technically need to run `sympify` internally, since I use `lambdify` to convert discovered expressions into callable functions. Any idea what to try?

**Comment by MilesCranmer** [comment]
It could be that because of this non-standard import method: https://github.com/cavalab/srbench/blob/045001a5ef1cee65e64d4ada368ff317c4544005/experiment/test_submission.py#L37-L39

is breaking the use of `locals()` internally to PySR when I try to set `locals` here: https://github.com/MilesCranmer/PySR/blob/4af4af74127216bd93bf5547f00a03bcc2dbbd91/pysr/sr.py#L1470?

**Comment by MilesCranmer** [comment]
The PR is also broken because this code:
```
folder=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep submission | sed 's|submission/\(.*\)/.*|\1|g' | head -n 1)
```
inside the github action YAML breaks when you edit `test_submission.py` since it also satisfies that regex.

I have therefore changed it to: `folder=$(ls submission | grep -v feat-example)`.

**Comment by MilesCranmer** [comment]
My tweak is to switch:
```python
    algorithm = importlib.__import__('methods.'+ml+'.regressor',globals(), 
                                  locals(), 
                                  ['*']) 
```
to 
```python
    if ml == 'pysr':
        from methods.pysr import regressor
        return regressor
````
inside `test_submission.py`. This seems to work locally as well as here, although as the test is stochastic I am not 100% sure this fixes it.

**Comment by MilesCranmer** [comment]
Nevermind, this isn't the issue.

I think the issue is that the model parameters get serialized inside a JSON file (?), which converts functions I pass into strings. (which can then not be converted back to functions).

I think if I hardcode some of these arguments into PySR itself (on a competition-specific branch), then the JSON serialization should work.

**Comment by lacava** [comment]
sounds good, looks like you figured it out! yes, we are storing runs in json and loading them to check symbolic equivalence. we won't use the model forms as lambdas / functions in that analysis. 

thanks for your submission!

**Pull request merged**
