### PR TITLE
Change GSGP code and interface

### PR DESCRIPTION
**Pull request by aboisbunon**
Hello!
Here is a proposition to improve GSGP's C code and Python interface with the following modifications:
* move the training part to the fit function in gsgp.py 
* handle a user-specified seed 
* get a bit more info if the program fails.

I ran a few tests which went well, I hope you'll find it interesting for the benchmark.
BTW, I've seen GSGP has been removed in the new benchmark article, is it because of the unavailability of an explicit model with this method?
Best regards,
AB

### CODE REVIEW

**Comment by lacava** [comment]
hi @adoisbunon, thanks for the contribution! sorry for the delay. 



> BTW, I've seen GSGP has been removed in the new benchmark article, is it because of the unavailability of an explicit model with this method?

We decided to leave GSGP out because 1) it was hacked together in our first experiment (e.g., it doesn't have a way to predict without passing labels or have good error reporting),  and I did not want to take responsibility for maintaining the codebase; 2) it did not perform well in our first benchmark and produces large models; 3) the developers were not responsive to questions/requests. 

I am happy to include it if you are willing to maintain it, but yes, we now require the methods to return a string version of the final model that can be assessed for symbolic equivalence. Is that possible?

**Comment by aboisbunon** [comment]
Hi @lacava ,
Thanks for taking the time to look at my contribution! To answer your questions about GSGP
> We decided to leave GSGP out because 1) it was hacked together in our first experiment (e.g., it doesn't have a way to predict without passing labels or have good error reporting), and I did not want to take responsibility for maintaining the codebase; 2) it did not perform well in our first benchmark and produces large models; 3) the developers were not responsive to questions/requests.

here is my answer: 1) this is actually the contribution I proposed, so it shouldn't be an issue anymore; 2) I had the same experience, sometimes it works well, but more often it doesn't...

As for the final model, I don't think it is possible to retrieve it as a readable text formula as it is growing exponentially... I tried but my code crashed rather quickly! Appart from that, I'm not sure it will require a lot of maintenance after that, but yeah, I could do it if needed.

Best,
AB

**Comment by aboisbunon** [comment]
Hi @lacava , no problem, it's done. Let me know if you need anything else!

**Review by lacava — CHANGES_REQUESTED** [review]
These changes look great! A couple additional items are needed to merge GSGP:

1. moving https://github.com/EpistasisLab/srbench/blob/master/experiment/methods/experimental/GSGPRegressor.py to `experiment/methods` so that the tests pick it up
2. GSGP needs to return or store complexity somehow, see [contribution guide](CONTRIBUTING.md). it can probably be iteratively calculated as trees are recombined
3. unless we make a separate track for black-box SR methods, we need the model string. Furthermore our plan is to require sympy compliance of models in the future to avoid all of the conversions we are currently doing in post-processing.

**Comment by lacava** [comment]
Hi @aboisbunon , unless you feel strongly about it, I suggest we go back to not including GSGP. If it produces infinite complexity and no formula, and in our previous tests underperforms linear methods, I don't think it's worth the hassle...

**Comment by aboisbunon** [comment]
Hi @lacava , no problem, I don't have strong feelings about it :)

**Pull request closed without merging**
