### PR TITLE
Transformation-Interaction-Rational SR (to be publised @ GECCO2022) and new installation procedures for ITEA

### PR DESCRIPTION
**Pull request by folivetti**
This PR adds two things:

- it updates ITEA installation script so that I don't need to provide a pre-compiled binary and `.so` files of the required libraries. Now it is capable of compiling the code with `cabal` and installing the python wrapper with `pip` without requiring `sudo`.
- it adds the new Transformation-Interaction-Rational SR algorithm to appear in GECCO 2022. The installation procedure is similar to ITEA. 

I have verified that:

- [x ] install scripts do not require sudo permissions. 
- [x ] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Also, besides checking the CI tests, I have tested both approaches on a local installation with an Intel DevCloud machine that doesn't have any of the required libraries pre-installed and don't provide sudo. So it should work in any (Linux) environment.

### CODE REVIEW

**Comment by lacava** [comment]
hm, it looks like only I can update the docker images because of the login. I need to change that.

**Comment by folivetti** [comment]
> hm, it looks like only I can update the docker images because of the login. I need to change that.

I was about to contact you to ask you that! I guess this failing test was not my fault :)

But there's no hurry. We can check that after the competition.

**Comment by lacava** [comment]
can you check that the update of ITEA in this PR matches the one used in PR #151 ? If so, we can close this one.

**Comment by folivetti** [comment]
> can you check that the update of ITEA in this PR matches the one used in PR #151 ? If so, we can close this one.

I had to make the same adjustments as I did with ITEA, it is now working with the CI!

**Pull request closed without merging**
