### PR TITLE
Competition2022---Only update the submission/TaylorGP folder 

### PR DESCRIPTION
**Pull request by KGAE-CUP**
Competition Checklist:
- [ ] title of this PR is meaningful, i.e. "method X for comp"
- [ ] A folder has been added to `submission/` with a meaningful name corresponding to your method name.
- The added folder includes these elements:
    - [ ] `metadata.yml` (**required**): A file describing your submission, following the descriptions in `example/metadata.yml`.  
    - [ ] `regressor.py` (**required**): a Python file that defines your method, named appropriately. See [submission/feat-example/regressor.py](https://github.com/cavalab/srbench/blob/Competition2022/submission/feat-example/regressor.py) for complete documentation.  It contains:
        - [ ]  `est`: a sklearn-compatible `Regressor` object. 
        - [ ]  `model(est, X=None)`: a function that returns a [**sympy-compatible**](https://www.sympy.org) string specifying the final model. It can optionally take the training data as an input argument. See [guidance below](###-returning-a-sympy-compatible-model-string). 
        - [ ]  `eval_kwargs` (optional): a dictionary that can specify method-specific arguments to `evaluate_model.py`.
        
    - [ ] `LICENSE` *(optional)* A license file
    - [ ] `environment.yml` *(optional)*: a [conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) that specifies dependencies for your submission. 
    - [ ] `install.sh` *(optional)*: a bash script that installs your method. 
    - [ ] additional files *(optional)*: you may include a folder containing the code for your method in the submission. 

I have verified that:

- [ ] install scripts do not require sudo permissions. 
- [ ] if pulled remotely, the source code is a fixed version (i.e., rerunning `install.sh` shouldn't pulll a different version of the code when run multiple times.) 

Refer to the [competition guide]( https://cavalab.org/srbench/competition-guide/ ) if you are unsure about any steps. 
If you don't find an answer, ping us!

### CODE REVIEW

**Comment by lacava** [comment]
@KGAE-CUP check my PR to your fork : https://github.com/KGAE-CUP/srbench/pull/2

need to rebase again to resolve conflicts/ updates to CI

**Comment by janoPig** [comment]
@KGAE-CUP I think the mapping should be like this
`for k, v in reversed(mapping.items()):`
because x_1 replace x_10 to someName0 and x_11 to someName1

**Review by lacava — CHANGES_REQUESTED** [review]
please discard changes to `experiment` and `official competitors` folders

**Comment by lacava** [comment]
> The above test code is in numpy format and there is no variable name, so it reported an error when I added the code of variable name replacement. If I delete the variable name replacement code, will it affect the later real competition?

yes, the function returned needs to use the correct variable names. see @janoPig 's comment. to add detail it should be something like 

```
def model(est, X):
    mapping = {'x_'+str(i):k for i,k in enumerate(X.columns)}
    new_model = est.model_
    for k,v in reversed(mapping.items()):
        new_model = new_model.replace(k,v)
```

**Pull request closed without merging**
