### PR TITLE
Updating hyperparameter of PS-Tree

### PR DESCRIPTION
**Pull request by hengzhe-zhang**
I find a new set of hyperparameters providing better general performance than the previous one. Thus, I hope to change the hyperparameter of my algorithm. As for providing a grid of six hyperparameters, I am afraid I am not able to do this in the near future. One reason is that I believe the default hyperparameter works well enough, and another reason is that I don't have enough computational resources to verify the grid search performance of PS-Tree.

### CODE REVIEW

**Comment by lacava** [comment]
Hi @hengzhe-zhang , seems you are trying to first run the benchmark then post the best parameters. This isn't how we designed the original experiment: we decided on parameter ranges beforehand without knowing how they would perform. 

Obviously we can't prevent the datasets from being used now that they are public (hence the [competition](https://cavalab.org/srbench/competition-2022/)'s focus on new datasets), but in order to compare results side by side in this repo, we have to make as level of a playing field as possible. That includes limiting evals for the current experiment to 500k. You can see our discussion here: https://github.com/cavalab/srbench/discussions/83#discussioncomment-2364850

This does not mean we can't make future benchmark comparisons with different experimental settings. For example in the competition, we will be doing away with required hyperparameter tuning for everyone - instead it will be up to competitors to decide if they want to tune in their own scripts. (see here: https://cavalab.org/srbench/competition-guide/#hyperparameter-tuning)

**Comment by lacava** [comment]
> I believe the default hyperparameter works well enough, and another reason is that I don't have enough computational resources to verify the grid search performance of PS-Tree.

To be clear, *we* will run your algorithm on these datasets (in as fair of a way as possible). You don't need to verify performance beforehand.

**Comment by hengzhe-zhang** [comment]
@lacava Thanks. I believe this thing could be viewed from two perspectives. From the perspective of competition, as you have mentioned, thanks to the existence of holdout testing datasets, I believe this is not a problem. The allowance of customized hyperparameter searching strategy is also a good setting. This may be beneficial for the development of self-adaptive evolutionary algorithms, because these algorithms may be much more efficient than the cross-validation strategy.

From the perspective of research, studying which prior knowledge is useful for a wide range of tasks is common in machine learning. For example, it is rather common to see researchers constantly finding more useful strategies to achieve better performance on fixed benchmark datasets, such as Cifar10 or ImageNet. In my case, I don't make any magical tricks on my algorithm, but just change my primitive set to the primitive set recommended by [1], and use random selection as the mating selection operator to encourage diversity. I think this prior knowledge does not overfit this benchmark. 

[1]. Nicolau M, Agapitos A. Choosing function sets with better generalisation performance for symbolic regression models[J]. Genetic Programming and Evolvable Machines, 2021, 22(1): 73-100.

**Comment by lacava** [comment]
@hengzhe-zhang to submit to the competition, please follow the competition guide: https://cavalab.org/srbench/competition-guide/

The competition is a separate item from submitting to SRBench. For the current version of SRBench, we must benchmark the methods according to the guidelines we established in [our paper](https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/hash/c0c7c76d30bd3dcaefc96f40275bdc0a-Abstract-round1.html) and I shared above. These are the requirements to ensure a fair comparison, they are not optional. 

We could change the benchmark setup in the future, but that will require all methods to be re-evaluated under the same conditions. 

> studying which prior knowledge is useful for a wide range of tasks is common in machine learning

What you are describing in this scenario is simply data leakage, not a "study of prior knowledge". 

here's a sample `hyper_params` dict:

```
hyper_params = dict(
                                  basic_primitive=[False,'optimal'], 
                                  n_pop=[10,25,50]
)
```

**Comment by hengzhe-zhang** [comment]
@lacava I understand what you have said. In order to compare existing algorithms and my algorithm fairly, I will provide a hyperparameter grid in the near future. 

By the way, I still have a question about your definition of data leakage. In the computer vision domain, people only submit papers to conferences after they have tuned their algorithm, such as ResNet, to outperform existing algorithms. Strictly speaking, this is a form of data leakage by your definition. However, if we allow all kinds of neural networks to freely tune the hyperparameter, not all of them will be able to compete with ResNet. Thus, the contribution of ResNet is still significant. One possible solution to alleviate the overfitting problem is to test the proposed algorithm on a variety of problems. For example, if ResNet performs well on CIFAR 100, ImageNet, and COCO, we can claim that the finding is significant even if there is a possibility of overfitting on all of these tasks.

**Comment by folivetti** [comment]
my 2 cents on this topic.

Whenever we have a fixed benchmark widely adopted by the scientific community, we are bound to specialize our methods to the performance criteria instead to an overall improvement. In other words, as time goes by, whenever someone creates a new method, if they have enough computational resource, they can test different hyperparameters until they find one that beats the current best approach (given that their method is competent).

This introduces an **unintentional** bias into the results since they are selecting the hyperparameters based on supposedly unknown data. Of course, this doesn't entirely takes away the merit of the method, as having a fixed hyperparameter that works well on a hundred different problems means that the method can find good results given the correct setting.

The way your method is presented right now, raises some questions such as:
- If we rerun the experiment with different seeds, would it still rank first?
- If we run it using different benchmarks, would it need different hyperparameter values?

The answer could be positive for your method, but we can't really be sure until we run different experiments. In my opinion, it would be safer for you to have a set of hyperparameters in  case anything changes in the current srbench for the next run.

About being unfair with the other approaches, one example that comes to mind is that I have observed some situations where the grid search doesn't choose the best parameter due to overfitting on small datasets. That happens because when splitting a small dataset, it changes the data distribution, so you actually optimize for something else. So, if you do have a fixed parameter set, your method isn't affected by that issue.

**Comment by lacava** [comment]
> By the way, I still have a question about your definition of data leakage. In the computer vision domain, people only submit papers to conferences after they have tuned their algorithm, such as ResNet, to outperform existing algorithms. Strictly speaking, this is a form of data leakage by your definition.

What you're describing is a problem in science in general, and in ML research specifically. And, yes, it is a form of data leakage as "meta-learning" on validation sets. This is explored in other work, e.g. 

- https://www.frontiersin.org/articles/10.3389/frobt.2014.00005/full
- https://epubs.siam.org/doi/10.1137/1.9781611972788.54

We cannot completely avoid it, but nonetheless our goal is to a better job benchmarking than the status quo. 

One approach we've taken is to include many different problems from different domains; another is to follow an experimental procedure that is as close to the same for all methods as possible. It is on this second 

We can't prevent submissions that have attempted to tune to PMLB prior to submission, but it isn't in the spirit of the benchmark. We included hyperparameter tuning specifically to give every method the chance to explore its hyperparameter space *as part of benchmarking*. 

So it doesn't make sense to have individual contributors running PMLB in the background and then updating their submission. All that does is hide the hyperparameter tuning step, add data leakage to it, and make your method look faster than it is, since we're comparing full CV time. 

In a similar vein it seems now that you might be delaying submitting a hyperparameter space to first test on PMLB. Please don't do this. Just make an educated guess within the confines of the experiment (500k evals, 6 total choices, 16 GB RAM, etc), as we did for the other methods. 

I would like to evaluate PSTree (and PySR) before the competition starts. So let's aim to have hyperparameter space decided by  end of tomorrow.  I'll ask the same for PySR.

**Comment by hengzhe-zhang** [comment]
@lacava Okay. I'm willing to provide a set of hyperparameters before the end of tomorrow. I was really busy these days.

**Comment by hengzhe-zhang** [comment]
@folivetti Thanks for your response. To be a fair comparison, I agree it would be better to run all algorithms under the same condition. 
The risk of the halving grid search method is also what I worry about. One better solution to this problem is to use a BO package to tune the hyperparameter. This way is popular now in the literature [1]. Nonetheless, the current evaluation protocol is not bad, and I think it is also acceptable to follow the current evaluation protocol.

[1]. Gorishniy Y, Rubachev I, Khrulkov V, et al. Revisiting deep learning models for tabular data[J]. Advances in Neural Information Processing Systems, 2021, 34.

**Pull request merged**
